"""Curated ticker-to-sector and ticker-to-theme mappings for MVP enrichment."""

TICKER_SECTORS: dict[str, str] = {
    "AAPL": "Technology",
    "MSFT": "Technology",
    "GOOGL": "Technology",
    "GOOG": "Technology",
    "AMZN": "Consumer Discretionary",
    "META": "Technology",
    "NVDA": "Technology",
    "TSLA": "Consumer Discretionary",
    "AMD": "Technology",
    "INTC": "Technology",
    "AVGO": "Technology",
    "CRM": "Technology",
    "ORCL": "Technology",
    "ADBE": "Technology",
    "NFLX": "Communication Services",
    "DIS": "Communication Services",
    "PYPL": "Financials",
    "V": "Financials",
    "MA": "Financials",
    "JPM": "Financials",
    "BAC": "Financials",
    "GS": "Financials",
    "MS": "Financials",
    "BRK.B": "Financials",
    "WMT": "Consumer Staples",
    "COST": "Consumer Staples",
    "PG": "Consumer Staples",
    "KO": "Consumer Staples",
    "PEP": "Consumer Staples",
    "JNJ": "Healthcare",
    "UNH": "Healthcare",
    "PFE": "Healthcare",
    "MRK": "Healthcare",
    "ABBV": "Healthcare",
    "LLY": "Healthcare",
    "XOM": "Energy",
    "CVX": "Energy",
    "COP": "Energy",
    "SLB": "Energy",
    "NEE": "Utilities",
    "SO": "Utilities",
    "LMT": "Industrials",
    "RTX": "Industrials",
    "BA": "Industrials",
    "CAT": "Industrials",
    "HON": "Industrials",
    "GE": "Industrials",
    "UPS": "Industrials",
    "AMT": "Real Estate",
    "PLD": "Real Estate",
    "APD": "Materials",
    "LIN": "Materials",
    "TSM": "Technology",
    "ASML": "Technology",
    "QCOM": "Technology",
    "MU": "Technology",
    "MRVL": "Technology",
    "ARM": "Technology",
    "PLTR": "Technology",
    "SNOW": "Technology",
    "NET": "Technology",
    "PANW": "Technology",
    "CRWD": "Technology",
    "ZS": "Technology",
    "COIN": "Financials",
    "SQ": "Financials",
    "SHOP": "Technology",
    "UBER": "Technology",
    "ABNB": "Consumer Discretionary",
    "SPY": "Index",
    "QQQ": "Index",
    "IWM": "Index",
    "VOO": "Index",
    "VTI": "Index",
}

TICKER_THEMES: dict[str, list[str]] = {
    "AAPL": ["Big Tech", "Consumer Electronics"],
    "MSFT": ["Big Tech", "Cloud", "AI Infrastructure"],
    "GOOGL": ["Big Tech", "Cloud", "AI Infrastructure"],
    "GOOG": ["Big Tech", "Cloud", "AI Infrastructure"],
    "AMZN": ["Big Tech", "Cloud", "E-Commerce"],
    "META": ["Big Tech", "AI Infrastructure", "Social Media"],
    "NVDA": ["AI Infrastructure", "Semiconductors", "GPU Computing"],
    "TSLA": ["Electric Vehicles", "Energy", "Autonomous Driving"],
    "AMD": ["Semiconductors", "AI Infrastructure"],
    "INTC": ["Semiconductors"],
    "AVGO": ["Semiconductors", "Networking"],
    "TSM": ["Semiconductors", "AI Infrastructure"],
    "ASML": ["Semiconductors", "Equipment"],
    "QCOM": ["Semiconductors", "Mobile"],
    "MU": ["Semiconductors", "Memory"],
    "MRVL": ["Semiconductors", "Networking"],
    "ARM": ["Semiconductors", "IP Licensing"],
    "CRM": ["Cloud", "Enterprise SaaS"],
    "ORCL": ["Cloud", "Enterprise SaaS"],
    "ADBE": ["Cloud", "Creative Software"],
    "SNOW": ["Cloud", "Data Infrastructure"],
    "PLTR": ["AI Infrastructure", "Defense", "Data Analytics"],
    "NET": ["Cloud", "Cybersecurity", "Edge Computing"],
    "PANW": ["Cybersecurity"],
    "CRWD": ["Cybersecurity"],
    "ZS": ["Cybersecurity"],
    "NFLX": ["Streaming", "Content"],
    "DIS": ["Streaming", "Content", "Theme Parks"],
    "PYPL": ["Fintech", "Payments"],
    "V": ["Fintech", "Payments"],
    "MA": ["Fintech", "Payments"],
    "SQ": ["Fintech", "Payments"],
    "COIN": ["Fintech", "Cryptocurrency"],
    "JPM": ["Banking", "Capital Markets"],
    "BAC": ["Banking"],
    "GS": ["Banking", "Capital Markets"],
    "MS": ["Banking", "Capital Markets"],
    "WMT": ["Retail", "E-Commerce"],
    "COST": ["Retail"],
    "SHOP": ["E-Commerce", "Cloud"],
    "UBER": ["Mobility", "Gig Economy"],
    "ABNB": ["Travel", "Platform"],
    "JNJ": ["Healthcare", "Pharma"],
    "UNH": ["Healthcare", "Insurance"],
    "PFE": ["Pharma", "Biotech"],
    "MRK": ["Pharma"],
    "ABBV": ["Pharma", "Biotech"],
    "LLY": ["Pharma", "Biotech", "GLP-1"],
    "XOM": ["Oil & Gas", "Energy"],
    "CVX": ["Oil & Gas", "Energy"],
    "COP": ["Oil & Gas", "Energy"],
    "SLB": ["Oil & Gas", "Oilfield Services"],
    "LMT": ["Defense", "Aerospace"],
    "RTX": ["Defense", "Aerospace"],
    "BA": ["Aerospace", "Commercial Aviation"],
    "CAT": ["Industrials", "Infrastructure"],
    "HON": ["Industrials", "Automation"],
    "GE": ["Industrials", "Aerospace", "Energy"],
}
